driver:
  name: vagrant
  forward_agent: yes
  synced_folders:
    - ['..', '/Users/vagrant/chef-workstation', "create: true, type: :rsync"]
  customize:
    cpus: 2
    memory: 2048
    storagectl:
      - name: SATA Controller
        hostiocache: "on"

provisioner:
  name: chef_zero

# only run one of these at a time if you are interested in using the
# omnibus package produced; the build process begins by cleaning up
# prior built artifacts in pkg/ which is shared across VMs
platforms:
  - name: centos-7
  - name: centos-6
  - name: debian-9
  - name: debian-8
  - name: debian-7
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: chef/macosx-10.11

suites:
  - name: default
    run_list: chef-workstation-builder::default
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        build_user_home:     /Users/vagrant
        build_dir:           /Users/vagrant/chef-workstation/omnibus
        install_dir:         /opt/chef-workstation
