# Documentation available at https://expeditor.chef.io/docs/getting-started/

# The name of the product keys for this product (from mixlib-install)
product_key:
  - chef-workstation

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-ws-notify

docker_images:
  - chefworkstation

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # allow bumping the major release via label
  major_bump_labels:
    - "Expeditor: Bump Version Major"
# https://expeditor.chef.io/docs/getting-started/subscriptions/#merge-actions
# The `merge_actions` key is a shortcut for the
# `pull_request_merged:<GITHUB_REPO>:<RELEASE_BRANCH>:*` subscription.
merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor: Skip Version Bump"
        - "Expeditor: Skip All"
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor: Skip Changelog"
        - "Expeditor: Skip All"
  - built_in:trigger_omnibus_release_build:
      ignore_labels:
        - "Expeditor: Skip Omnibus"
        - "Expeditor: Skip All"
      only_if: built_in:bump_version

pipelines:
  - verify:
      description: Pull Request validation tests
  - omnibus/release
  - omnibus/adhoc:
      definition: .expeditor/release.omnibus.yml
      env:
        - ADHOC: true

subscriptions:
  - workload: artifact_published:unstable:chef-workstation:{{version_constraint}}
    actions:
      - built_in:build_docker_image
  - workload: artifact_published:current:chef-workstation:{{version_constraint}}
    actions:
      - built_in:tag_docker_image
  - workload: artifact_published:stable:chef-workstation:{{version_constraint}}
    actions:
      - built_in:rollover_changelog
      - bash:.expeditor/update_dockerfile.sh
      - built_in:tag_docker_image   
      - bash:.expeditor/publish-release-notes.sh
      - bash:.expeditor/purge-cdn.sh
      - bash:.expeditor/announce-release.sh
  - workload: artifact_published:stable:chefdk:3*
    actions:
      - bash:.expeditor/update_chefdk_to_stable.sh
  - workload: chef/chef-workstation-app:master_completed:pull_request_merged:chef/chef-workstation-app:master:*
    actions:
      - bash:.expeditor/update_chef-workstation-app_to_latest.sh
  - workload: chef/delivery-cli:master_completed:pull_request_merged:chef/delivery-cli:master:*
    actions:
      - bash:.expeditor/update_delivery-cli_to_latest.sh
